language: R
sudo: false
cache: packages
warnings_are_errors: false
before_install:
- openssl aes-256-cbc -K $encrypted_39c05ab0bd98_key -iv $encrypted_39c05ab0bd98_iv
  -in tests/testthat/twitter_tokens.enc -out tests/testthat/twitter_tokens -d
r_github_packages:
- jimhester/covr
after_success:
- Rscript -e 'covr::codecov(function_exclusions = c("print\\.", "plot\\.", "create_token",
  "load_tokens", "nanull", "is_empty_list", "global_token_finder", "system_tokens", "post_tweet", "all_tw"))'
